# Generated by Django 5.2.9 on 2025-12-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('donation_method', models.CharField(choices=[('Direct', 'Direct'), ('Pickup', 'Pickup')], max_length=20)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.requireditem')),
            ],
        ),
    ]
