# Generated by Django 5.2.9 on 2025-12-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.requireditem'),
        ),
    ]
