# Generated by Django 5.2.9 on 2025-12-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Medicine', 'Medicine'), ('Blanket', 'Blanket'), ('Water', 'Water')], max_length=100)),
                ('required_quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
