# Generated by Django 5.2.9 on 2025-12-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(default='Collected', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
